baseURL = "http://routley.io/"
languageCode = "en-gb"
title = "James Routley"

# Enable syntax highlighting in markdown code snippets
pygmentsCodeFences = true
pygmentsStyle = "vs"

# Publish to /docs, where GitHub pages will serve from
publishDir = "docs"
